version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content/themes/wp-react-theme:/app/wp-content/themes/wp-react-theme
      - ./wp-content/w3tc-config:/app/wp-content/w3tc-config
      - ./wp-content/uploads:/app/wp-content/uploads
      - ./sw.js:/app/sw.js
      - ./appcache:/app/appcache
    environment:
      DB_PASS: root
      PERMALINKS: archives/%post_id%/%postname%/
      PLUGINS: >-
        [yoast-to-rest-api]https://github.com/niels-garve/yoast-to-rest-api/archive/1.4.1.zip,
        wp-optimize,
        wp-migrate-db,
        wordpress-seo,
        w3-total-cache,
        tinymce-clear-buttons,
        regenerate-thumbnails,
        https-redirection,
        disable-emojis,
        custom-post-type-ui,
        [Basic-Auth]https://github.com/WP-API/Basic-Auth/archive/master.zip,
        amazon-web-services,
        amazon-s3-and-cloudfront,
        advanced-custom-fields,
        acf-to-rest-api,
        acf-content-analysis-for-yoast-seo
      ENVIRONMENT: development
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80

volumes:
  data:
